"""empty message

Revision ID: c41c7df31638
Revises: 50e8ed6d884b
Create Date: 2026-09-16 19:13:39.230258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41c7df31638'
down_revision = '50e8ed6d884b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trailer', sa.String(length=100), nullable=True))
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('trailer')

    # ### end Alembic commands ###
